# Generated by Django 2.1.2 on 2018-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('maximum_capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('enter_time', models.DateTimeField(verbose_name='time entered')),
                ('leave_time', models.DateTimeField(verbose_name='time left')),
                ('student_computing_id', models.CharField(max_length=200)),
                ('student_location', models.CharField(max_length=200)),
            ],
        ),
    ]
