# Generated by Django 2.1.1 on 2018-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('maximum_capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
            ],
        ),
    ]
