# Generated by Django 2.1.1 on 2018-11-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='iconsize',
            field=models.CharField(default='', max_length=200),
        ),
    ]
