# Generated by Django 2.1.1 on 2018-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='percent_full',
            field=models.IntegerField(default=0),
        ),
    ]
