# Generated by Django 2.1.1 on 2018-10-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('enter_time', models.DateTimeField()),
                ('student_computing_id', models.CharField(max_length=200)),
                ('student_location', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
