# Generated by Django 2.1.1 on 2018-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pwds',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enter_time',
            field=models.DateTimeField(null=True),
        ),
    ]
